version: 2.1

orbs:
  win: circleci/windows@4.1.1

jobs:
  build_macos:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      # Steps adapted from the official flutter orb
      - restore_cache:
          keys:
            - flutter-2.10.5-{{ arch }}
      - run:
          name: Install Flutter SDK if not exists
          command: |
            if [ ! -d ~/development/flutter ]; then
              mkdir -p ~/development
              curl -o flutter_sdk.zip https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_2.10.5-stable.zip
              unzip -qq flutter_sdk.zip -d ~/development
            fi
            echo 'export PATH=~/development/flutter/bin:$PATH' >> $BASH_ENV
      - run: flutter doctor
      - save_cache:
          key: flutter-2.10.5-{{ arch }}
          paths:
            - ~/development
      - run:
          name: Enable desktop
          command: flutter config --enable-macos-desktop
      - run:
          name: Run build
          command: flutter build macos
      - run:
          name: Compress Artifacts
          command: tar -C build/macos/Build/Products/Release -cvzf macos.tar.gz .
      - store_artifacts:
          path: macos.tar.gz
  build_windows:
    executor: win/default
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          flutter_version: 2.10.5
      - run:
          name: Enable desktop
          command: flutter config --enable-windows-desktop
      - run:
          name: Run build
          command: flutter build windows
      - run:
          name: Prob dir
          command: ls build && ls build/windows && ls build/windows/x64
      # - run:
      #     name: Compress Artifacts
      #     command: tar -C build/macos/Build/Products/Release -cvzf macos.tar.gz .
      # - store_artifacts:
      #     path: macos.tar.gz

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build:
    jobs:
      - build_macos
