# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Documentation

on:
  push:
    branches: [ main ]

jobs:
  doc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.2'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get && flutter pub global activate dartdoc

      - name: Generate documentation
        run: flutter pub global run dartdoc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PA_TOKEN }}
          external_repository: lunacd/omnilore_documentation
          publish_branch: main
          publish_dir: ./doc/api
